
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  pool: 5

deveplopment:
  <<: *default
  database: seeks_development


test:
  <<: *default
  database: seeks_test


#
production:
  <<: *default
  database: seeks_production
  password: <%= ENV['SEEKS_DATABASE_PASSWORD'] %>
